spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: jaimatadi
    url: jdbc:mysql://localhost/RedishCache?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
  jpa:
    database-platform: org.hibernate.dialect..MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  cache:
    redis:
      cache-null-values: true
      time-to-live: 6000
    type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"    
